"""empty message

Revision ID: e005c7d9f45f
Revises: 
Create Date: 2024-03-14 15:23:40.701701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e005c7d9f45f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_table'))
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_table'))
    )
    op.create_table('budget_data_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_budget', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category_table.id'], name=op.f('fk_budget_data_table_category_id_category_table')),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_budget_data_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_data_table'))
    )
    op.create_table('transaction_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category_table.id'], name=op.f('fk_transaction_table_category_id_category_table')),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_transaction_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_table'))
    )
    op.create_table('user_data_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('savings', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_user_data_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_data_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data_table')
    op.drop_table('transaction_table')
    op.drop_table('budget_data_table')
    op.drop_table('user_table')
    op.drop_table('category_table')
    # ### end Alembic commands ###
